language: php

php:
  - 5.5.9
  - 5.6
  - 7.0

sudo: false

install:
  - composer self-update
  - composer install --no-interaction
script:
  - php vendor/bin/phpunit
after_success:
  - php vendor/bin/coveralls -v
